version: '3.8'

services:
  server:
    image: temp_sre_server
    container_name: animal_server
    ports:
      - "5000:5000"  
    networks:
      - animal_network
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
    #depends_on:
    #  - tempo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client:
    image: temp_sre_client
    container_name: animal_client
    ports:
      - "8000:8000"  
    environment:
      - SERVER_URL=http://animal_server:5000/animals
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
    depends_on:
      - server
    #  - tempo
    networks:
      - animal_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: SRE_cand_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"  # Expose Prometheus UI on port 9090
    networks:
      - animal_network

  grafana:
    image: grafana/grafana:latest
    container_name: SRE_cand_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - animal_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  

networks:
  animal_network:
    driver: bridge

