global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'animal_server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['animal_server:5000']  

  - job_name: 'animal_client'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['animal_client:8000']  

